version: '3'

services:
  malware-notifications-db:
    container_name: malware-notifications-db
    image: postgres:13.5
    ports:
      - "5432:5432"
    volumes:
      - malware-notifications-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=malware-notifications
      - POSTGRES_PASSWORD=malware-notifications
      - POSTGRES_DB=malware-notifications
    networks:
      - malware-notifications-network
  malware-notifications:
    container_name: malware-notifications
    image: malware-notifications
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - malware-notifications-db
    networks:
      - malware-notifications-network

volumes:
  malware-notifications-db:
    driver: local

networks:
  malware-notifications-network:
    driver: bridge
