version: '3'

services:
  malware-notifications-db:
    container_name: malware-notifications-db
    image: postgres:13.5
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - malware-notifications-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-malware-notifications}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-malware-notifications}
      - POSTGRES_DB=${DB_NAME:-DB_malware-notifications}
    networks:
      - malware-notifications-network
  malware-notifications:
    container_name: malware-notifications
    image: malware-notifications
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - malware-notifications-db
    networks:
      - malware-notifications-network
    environment:
      - DB_HOST=malware-notifications-db
      - DB_PORT=5432
      - DB_NAME=malware-notifications
      - DB_USER=malware-notifications
      - DB_PASSWORD=malware-notifications

volumes:
  malware-notifications-db:
    driver: local

networks:
  malware-notifications-network:
    driver: bridge
